schedule-x/schedule-x

website/pages/docs/calendar/_meta.json, website/pages/docs/calendar/calendars.mdx, website/pages/docs/calendar/configuration.mdx
=> docs: add documentation for dayBoundaries and calendars

packages/calendar/src/index.ts, packages/calendar/src/utils/stateful/preact-view/preact-view.ts, packages/calendar/src/views/day/index.ts, packages/calendar/src/views/month-agenda/index.ts, packages/calendar/src/views/month-grid/index.ts, packages/calendar/src/views/week/index.ts, packages/shared/package.json, packages/shared/src/index.ts, packages/shared/src/types/calendar/view.ts, website/pages/docs/calendar/custom-views.mdx
=> feat: expose APIs for creating custom views

package.json, packages/calendar/package.json, packages/scroll-controller/package.json, packages/shared/package.json, packages/theme-default/src/components/date-picker/month-view/month-view-header.scss
=> feat: hover animation for button in date picker

README.md, development/calendar/main.tsx, website/pages/docs/calendar/plugins.mdx
=> docs: document scroll plugin and custom plugins

website/pages/docs/calendar/react.mdx
=> docs: add info about nextjs

website/components/pages/__data__/calendar-code.ts, website/components/pages/demo-calendar.tsx, website/components/pages/demo.module.scss, website/pages/docs/calendar/react.mdx, website/theme/index.scss
=> docs: remove note on nextjs problem

development/calendar/main.tsx, packages/scroll-controller/package.json, packages/scroll-controller/src/scroll-controller.plugin.ts
=> fix: drag and drop triggers scroll plugin

README.md, website/pages/docs/calendar/configuration.mdx
=> chore: update readme

packages/calendar/src/components/week-grid/__test__/date-grid-event/display.spec.tsx, packages/calendar/src/components/week-grid/date-grid-event.tsx, packages/calendar/src/components/week-grid/time-grid-event.tsx, packages/calendar/src/utils/stateful/hooks/use-event-interactions.tsx, packages/calendar/src/views/month-grid/components/month-grid-event.tsx, packages/drag-and-drop/src/date-grid-drag-handler.impl.ts, packages/drag-and-drop/src/drag-and-drop-plugin.impl.ts, packages/drag-and-drop/src/time-grid-drag-handler.impl.ts, packages/event-modal/src/event-modal-plugin.impl.ts, packages/event-modal/src/event-modal.tsx, packages/shared/src/interfaces/drag-and-drop/drag-handler-dependencies.interface.ts, packages/shared/src/interfaces/event-modal/event-modal.plugin.ts, packages/shared/src/interfaces/shared/event-coordinates.ts, packages/shared/src/utils/stateless/dom/get-event-coordinates.ts, packages/shared/src/utils/stateless/dom/is-touch-event.ts, packages/theme-default/src/components/calendar/week-grid/time-grid-event.scss
=> Touchscreen support

packages/translations/src/index.ts, packages/translations/src/locales/ru-RU/calendar.ts, packages/translations/src/locales/ru-RU/date-picker.ts, packages/translations/src/locales/ru-RU/index.ts
Add Russian language support.
Issue Feature link: https://github.com/schedule-x/schedule-x/issues/158
I have tested it locally, everything is correct.
=> feat: add russian language support

packages/translations/src/index.ts, packages/translations/src/locales/ko-KR/calender.ts, packages/translations/src/locales/ko-KR/date-picker.ts, packages/translations/src/locales/ko-KR/index.ts, packages/translations/src/translator/__test__/translate.spec.ts, website/pages/docs/calendar/configuration.mdx
resolve #178 
For example:  
1. Open `main.tsx` files located in the `./development directory`.
2. Change the `locale` configuration in both `createCalendar` and `createDatePicker` to:
```
locale: 'ko-KR'
```
3. Run the development server with the command:
```
npm run dev
```
=> feat: add korean language support

development/calendar/main.tsx, development/date-picker/main.tsx, package-lock.json, packages/translations/src/index.ts, packages/translations/src/locales/fr-FR/calendar.ts, packages/translations/src/locales/fr-FR/date-picker.ts, packages/translations/src/locales/fr-FR/index.ts, packages/translations/src/translator/__test__/translate.spec.ts, website/pages/docs/calendar/configuration.mdx
Add french lang for this package.
=> feat: add french lang

packages/translations/src/locales/da-DK/calendar.ts
=> Fix Typo in Danish Lang

packages/translations/src/index.ts, packages/translations/src/locales/pl-PL/calendar.ts, packages/translations/src/locales/pl-PL/date-picker.ts, packages/translations/src/locales/pl-PL/index.ts
Add Polish language support.
I have tested it locally, everything is correct.
=> Add support for polish language

packages/translations/src/index.ts, packages/translations/src/locales/es-ES/calendar.ts, packages/translations/src/locales/es-ES/date-picker.ts, packages/translations/src/locales/es-ES/index.ts
Add Spanish support language
Set `es-ES` as locale config and check different views.
=> Add support for Spanish language

packages/calendar/src/calendar.app.ts, packages/event-modal/src/__test__/event-modal.spec.tsx, packages/event-modal/src/__test__/utils.tsx, packages/event-modal/src/event-modal.tsx, packages/shared/src/interfaces/calendar/custom-component-fns.ts, packages/theme-default/src/components/calendar/event-modal/wrapper.scss
Added the ability to customize event modals to the calendar
For example:  
1. Add the eventModal plugin to the project
2. Add eventModal as a custom component
3. Create a custom eventModal component and add it to the custom components attribute.
=> Added the ability to customize event modals to the calendar's eventModal plugin. 

cypress/e2e/calendar/001-drag-and-drop.disabled.ts, cypress/tsconfig.json
=> fix: local error when starting vite devserver

packages/translations/src/index.ts, packages/translations/src/locales/sk-SK/calendar.ts, packages/translations/src/locales/sk-SK/date-picker.ts, packages/translations/src/locales/sk-SK/index.ts, website/pages/docs/calendar/supported-languages.mdx
Add feature https://github.com/schedule-x/schedule-x/issues/312
For example:  
Set sk-SK as locale config and check different views.
=> feat: add Slovak language support(#312)

packages/translations/src/index.ts, packages/translations/src/locales/mk-MK/calendar.ts, packages/translations/src/locales/mk-MK/date-picker.ts, packages/translations/src/locales/mk-MK/index.ts, website/pages/docs/calendar/supported-languages.mdx
This PR adds Macedonian language support.
Set locale to `mk-MK` and check the content (if you can read Macedonian :) )
=> feat: adding macedonian language support

packages/translations/src/index.ts, packages/translations/src/locales/tr-TR/calendar.ts, packages/translations/src/locales/tr-TR/date-picker.ts, packages/translations/src/locales/tr-TR/index.ts, website/pages/docs/calendar/supported-languages.mdx
This PR solves the issue as described in #335 
Set the locale in the datepicker or calendar config to tr-TR, i.e. locale: 'tr-TR',
=> feat: adding Turkish language support (#335)

packages/calendar/src/index.ts
=> feat(calendar): expose interfaces

development/calendar/main.tsx, packages/translations/src/index.ts, packages/translations/src/locales/cs-CZ/calendar.ts, packages/translations/src/locales/cs-CZ/date-picker.ts, packages/translations/src/locales/cs-CZ/index.ts, website/pages/docs/calendar/supported-languages.mdx
**Premium**
This PR adds support for Czech language.
For example:  
1. Set the locale in the date-picker or calendar config to 'cs-CZ'
=> Czech language

website/pages/docs/calendar/angular.mdx
=> docs: add documentation for angular templates

packages/events-service/src/__test__/events-service-plugin-impl.spec.ts, packages/shared/src/index.ts, packages/shared/src/interfaces/plugin.interface.ts, packages/shared/src/types/recursive-partial.ts
- add pluginbase to exports
- use recursivepartial to prevent third party plugins from breaking when properties are added
=> fix: improve tolerance for app interface

development/calendar/main.tsx, packages/translations/src/index.ts, packages/translations/src/locales/et-EE/calendar.ts, packages/translations/src/locales/et-EE/date-picker.ts, packages/translations/src/locales/et-EE/index.ts, website/pages/docs/calendar/supported-languages.mdx
##This PR is adding new language: Estonian language, Estonian region, locale et-EE
set locale configuration to 'et-EE'
const calendar = createCalendar({
//......
locale: 'et-EE',
//.....
)}
=> added Estonian language support

packages/translations/src/index.ts, packages/translations/src/locales/ca-ES/calendar.ts, packages/translations/src/locales/ca-ES/date-picker.ts, packages/translations/src/locales/ca-ES/index.ts, packages/translations/src/locales/et-EE/calendar.ts, website/pages/docs/calendar/supported-languages.mdx
=> Added Catala translation

development/calendar/main.tsx, packages/calendar/src/components/__test__/callbacks.spec.tsx, packages/calendar/src/components/week-grid/date-grid-event.tsx, packages/calendar/src/components/week-grid/time-grid-event.tsx, packages/calendar/src/utils/stateless/events/invoke-on-event-double-click-callback.ts, packages/calendar/src/utils/stateless/testing/click-by-text.ts, packages/calendar/src/views/month-agenda/components/__test__/month-agenda-day.spec.tsx, packages/calendar/src/views/month-agenda/components/month-agenda-day.tsx, packages/calendar/src/views/month-agenda/components/month-agenda-event.tsx, packages/calendar/src/views/month-grid/components/month-grid-event.tsx, packages/shared/src/interfaces/calendar/listeners.interface.ts, website/pages/docs/calendar/configuration.mdx
**Premium**
Implement `onDoubleClickAgendaDate` and `onDoubleClickEvent`.
**onDoubleClickAgendaDate**
1. Create a calendar with `createViewMonthAgenda` as view and a `onDoubleClickAgendaDate` function inside the callbacks property.
2. Double click any date and it will get called.
**onDoubleClickEvent**
1. Create a calendar with any view and a `onDoubleClickEvent` function inside the callbacks property.
2. Double click any event and it will get called.
=> Implement onDoubleClickAgendaDate and onDoubleClickEvent

packages/translations/src/index.ts, packages/translations/src/locales/lt-LT/calendar.ts, packages/translations/src/locales/lt-LT/date-picker.ts, packages/translations/src/locales/lt-LT/index.ts, website/pages/docs/calendar/supported-languages.mdx
**Premium**
Adds `lt-LT` (Lithuanian 🇱🇹 ) locale
=> feat(locale): add lt-LT locale

website/pages/docs/calendar/plugins/draw.mdx
=> docs(draw): onFinishDrawing callback

website/components/code-examples/nextjs-calendar.mdx
**Premium**
Adds use client directive to NextJS example code snippet.
Read the docs.
=> fix(docs): Add use client directive to nextjs example.

packages/translations/src/index.ts, packages/translations/src/locales/ro-RO/calendar.ts, packages/translations/src/locales/ro-RO/date-picker.ts, packages/translations/src/locales/ro-RO/index.ts, website/pages/docs/calendar/language.mdx
**Premium**
Translation to ro_RO (romanian language).
For example:  
1. Set the language to ro_RO
2. Labels should be displayed in romanian.
=> feat: add ro_RO translation

packages/shared/src/utils/stateless/time/format-conversion/date-format/date-format-localized-rules.ts, packages/translations/src/index.ts, packages/translations/src/locales/fr-CH/date-picker.ts, packages/translations/src/locales/fr-CH/index.ts, packages/translations/src/translator/__test__/translate.spec.ts, website/pages/docs/calendar/language.mdx
**Premium**
Add frCH lang, the only relevant change is the date format DD.MM.YYYY
For example:  
1. Set locale to fr-CH
=> feat: add fr-CH translation

packages/calendar/src/index.ts, packages/current-time/src/current-time-plugin.impl.ts, packages/shared/src/index.ts
**Premium**
Export some utils to use in custom views.
For example:  
=> Export some utils to use in custom views.

website/app/layout.tsx
- [ X] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [ X] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [ X] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
Add Discord link to the navbar
For example:  
1. Run website 
2. Check top left, appened to the search bar theres a discord icon.
3. Confirm that on clicking you are redirected to Discord
=> fix: add discord icon
